language: php

php:
  - '8.2'

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

before_install:
  - cp .env.example .env
  - composer self-update

install:
  - composer install --no-interaction --prefer-dist

before_script:
  # switch to sqlite for CI
  - php artisan key:generate
  - sed -i 's/^DB_CONNECTION=.*/DB_CONNECTION=sqlite/' .env
  - sed -i 's|^DB_DATABASE=.*|DB_DATABASE='database/database.sqlite'|' .env
  - touch database/database.sqlite
  - php artisan migrate --force --database=sqlite

script:
  # Run Pest if present, otherwise fallback to PHPUnit
  - if [ -f vendor/bin/pest ]; then vendor/bin/pest; else vendor/bin/phpunit; fi
